server:
  port: 2323

spring:
  application:
    name: shoppie

  datasource:
    url: jdbc:postgresql://localhost:5432/shoppie_db
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    jwt:
      secret-key: tVpNqEwCvjRUNfr8wCbchN0rKtl8YntFhh4RBJ2O6Ol
      access-token-expiration: 900000
      refresh-token-expiration: 604800000

  mail:
    host: smtp.gmail.com
    port: 587
    username: sanan.tahmazli2329@gmail.com
    password: glchngaqyfvlumkj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    cache: false
