server:
  port: 2323

spring:
  application:
    name: shoppie

  datasource:
    url: jdbc:postgresql://localhost:5432/shoppie_db
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: sanan.tahmazli2329@gmail.com
    password: glchngaqyfvlumkj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    cache: false
